package defpackage;

import android.content.res.Resources;
import android.graphics.Color;
import android.graphics.Point;
import android.graphics.Rect;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.ShapeDrawable;
import android.graphics.drawable.StateListDrawable;
import android.graphics.drawable.shapes.RoundRectShape;
import android.os.Build.VERSION;
import android.support.v4.view.ViewCompat;
import android.view.Display;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AlphaAnimation;
import android.view.animation.Animation;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.ImageView.ScaleType;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout.LayoutParams;
import android.widget.TextView;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import scanpay.it.ScanPayActivity;

public final class O extends RelativeLayout {
    private final ScanPayActivity a;
    private final FrameLayout b;
    private N c = new N(this.a, this.a);
    private int d;

    public O(ScanPayActivity scanPayActivity) {
        super(scanPayActivity);
        this.a = scanPayActivity;
        setGravity(80);
        setLayoutParams(new LayoutParams(-1, -1));
        this.b = new FrameLayout(scanPayActivity);
        this.b.setId(18);
        addView(this.b);
        setId(43);
        Display defaultDisplay = this.a.getWindowManager().getDefaultDisplay();
        if (VERSION.SDK_INT >= 13) {
            Point point = new Point();
            defaultDisplay.getSize(point);
            this.d = point.x;
        } else {
            this.d = defaultDisplay.getWidth();
        }
        int i = (int) ((((float) this.d) * 640.0f) / 480.0f);
        this.c.setLayoutParams(new LayoutParams(this.d, i));
        this.c.setId(8);
        ViewGroup.LayoutParams layoutParams = new LayoutParams(this.d, i);
        layoutParams.addRule(13);
        this.b.addView(this.c);
        this.b.setLayoutParams(layoutParams);
        defaultDisplay = this.a.getWindowManager().getDefaultDisplay();
        if (VERSION.SDK_INT >= 13) {
            point = new Point();
            defaultDisplay.getSize(point);
            i = point.x;
        } else {
            i = defaultDisplay.getWidth();
        }
        int i2 = (int) ((((float) i) * 640.0f) / 480.0f);
        int i3 = (int) ((((float) i) * BitmapDescriptorFactory.HUE_MAGENTA) / 320.0f);
        int i4 = (int) ((((float) i3) * 200.0f) / BitmapDescriptorFactory.HUE_MAGENTA);
        int i5 = (int) (12.0f * (((float) i3) / BitmapDescriptorFactory.HUE_MAGENTA));
        int i6 = ((i - i3) / 2) + i5;
        int i7 = ((i2 - i4) / 2) + i5;
        i = ((i - i4) / 2) + i5;
        i2 = ((i2 - i3) / 2) + i5;
        Rect rect = new Rect(i6, i7, (i6 + i3) - (i5 << 1), (i7 + i4) - (i5 << 1));
        Rect rect2 = new Rect(i, i2, (i4 + i) - (i5 << 1), (i3 + i2) - (i5 << 1));
        View q = new Q(this.a, new Rect[]{rect, rect2});
        q.setId(44);
        q.setBackgroundColor(ViewCompat.MEASURED_STATE_MASK);
        if (VERSION.SDK_INT >= 11) {
            q.setAlpha(0.49019608f);
        } else {
            Animation alphaAnimation = new AlphaAnimation(0.49019608f, 0.49019608f);
            alphaAnimation.setDuration(0);
            alphaAnimation.setFillAfter(true);
            q.setAnimation(alphaAnimation);
        }
        this.b.addView(q);
        q = new LinearLayout(this.a);
        q.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        q.setOrientation(1);
        q.setGravity(17);
        View relativeLayout = new RelativeLayout(this.a);
        relativeLayout.setLayoutParams(new LinearLayout.LayoutParams(a(298.0f), a(204.0f)));
        relativeLayout.setId(17);
        View imageView = new ImageView(this.a);
        ViewGroup.LayoutParams layoutParams2 = new LayoutParams(-1, -1);
        layoutParams2.setMargins(a(9.0f), a(9.0f), a(9.0f), a(9.0f));
        imageView.setLayoutParams(layoutParams2);
        imageView.setId(9);
        imageView.setScaleType(ScaleType.FIT_XY);
        View imageView2 = new ImageView(this.a);
        imageView2.setLayoutParams(new LayoutParams(-1, -1));
        imageView2.setScaleType(ScaleType.FIT_XY);
        imageView2.setImageBitmap(os.a("card_bordershadow"));
        imageView2.setId(19);
        relativeLayout.addView(imageView);
        relativeLayout.addView(imageView2);
        q.addView(relativeLayout);
        this.b.addView(q);
        relativeLayout = new RelativeLayout(this.a);
        ViewGroup.LayoutParams layoutParams3 = new LayoutParams(-1, this.c.getLayoutParams().height);
        layoutParams3.addRule(14);
        layoutParams3.addRule(15);
        relativeLayout.setLayoutParams(layoutParams3);
        relativeLayout.setId(5);
        if (VERSION.SDK_INT >= 13) {
            Point point2 = new Point();
            this.a.getWindowManager().getDefaultDisplay().getSize(point2);
            i = point2.x;
        } else {
            i = this.a.getWindowManager().getDefaultDisplay().getWidth();
        }
        i = (int) ((((float) i) * BitmapDescriptorFactory.HUE_MAGENTA) / 320.0f);
        i3 = (int) ((((float) i) * 200.0f) / BitmapDescriptorFactory.HUE_MAGENTA);
        i4 = (int) (12.0f * (((float) i) / BitmapDescriptorFactory.HUE_MAGENTA));
        i5 = (int) (50.0f * (((float) i) / BitmapDescriptorFactory.HUE_MAGENTA));
        View relativeLayout2 = new RelativeLayout(this.a);
        relativeLayout2.setId(4);
        ViewGroup.LayoutParams layoutParams4 = new LayoutParams(i, i3);
        layoutParams4.addRule(14);
        layoutParams4.addRule(15);
        relativeLayout2.setLayoutParams(layoutParams4);
        View linearLayout = new LinearLayout(this.a);
        linearLayout.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams5 = new LayoutParams(i4, i5);
        layoutParams5.addRule(10);
        layoutParams5.addRule(9);
        linearLayout.setLayoutParams(layoutParams5);
        View linearLayout2 = new LinearLayout(this.a);
        linearLayout2.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams6 = new LayoutParams(i5, i4);
        layoutParams6.addRule(10);
        layoutParams6.addRule(9);
        linearLayout2.setLayoutParams(layoutParams6);
        View linearLayout3 = new LinearLayout(this.a);
        linearLayout3.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams7 = new LayoutParams(i4, i5);
        layoutParams7.addRule(10);
        layoutParams7.addRule(11);
        linearLayout3.setLayoutParams(layoutParams7);
        View linearLayout4 = new LinearLayout(this.a);
        linearLayout4.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams8 = new LayoutParams(i5, i4);
        layoutParams8.addRule(11);
        layoutParams8.addRule(10);
        linearLayout4.setLayoutParams(layoutParams8);
        View linearLayout5 = new LinearLayout(this.a);
        linearLayout5.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams9 = new LayoutParams(i4, i5);
        layoutParams9.addRule(12);
        layoutParams9.addRule(9);
        linearLayout5.setLayoutParams(layoutParams9);
        View linearLayout6 = new LinearLayout(this.a);
        linearLayout6.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams10 = new LayoutParams(i5, i4);
        layoutParams10.addRule(9);
        layoutParams10.addRule(12);
        linearLayout6.setLayoutParams(layoutParams10);
        View linearLayout7 = new LinearLayout(this.a);
        linearLayout7.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams11 = new LayoutParams(i4, i5);
        layoutParams11.addRule(12);
        layoutParams11.addRule(11);
        linearLayout7.setLayoutParams(layoutParams11);
        View linearLayout8 = new LinearLayout(this.a);
        linearLayout8.setBackgroundColor(-1);
        ViewGroup.LayoutParams layoutParams12 = new LayoutParams(i5, i4);
        layoutParams12.addRule(11);
        layoutParams12.addRule(12);
        linearLayout8.setLayoutParams(layoutParams12);
        relativeLayout2.addView(linearLayout);
        relativeLayout2.addView(linearLayout2);
        relativeLayout2.addView(linearLayout4);
        relativeLayout2.addView(linearLayout3);
        relativeLayout2.addView(linearLayout5);
        relativeLayout2.addView(linearLayout6);
        relativeLayout2.addView(linearLayout7);
        relativeLayout2.addView(linearLayout8);
        View imageView3 = new ImageView(this.a);
        imageView3.setId(39);
        layoutParams4 = new LayoutParams(i, i3);
        layoutParams4.addRule(14);
        layoutParams4.addRule(15);
        imageView3.setLayoutParams(layoutParams4);
        imageView3.setImageBitmap(os.a("card_example"));
        imageView3.setScaleType(ScaleType.CENTER_CROP);
        if (VERSION.SDK_INT >= 16) {
            imageView3.setImageAlpha(90);
        } else {
            imageView3.setAlpha(90);
        }
        linearLayout = new ImageView(this.a);
        linearLayout.setId(41);
        layoutParams5 = new LayoutParams(i3, i);
        layoutParams5.addRule(14);
        layoutParams5.addRule(15);
        linearLayout.setLayoutParams(layoutParams5);
        linearLayout.setImageBitmap(os.a("card_example_left"));
        linearLayout.setScaleType(ScaleType.CENTER_CROP);
        if (VERSION.SDK_INT >= 16) {
            linearLayout.setImageAlpha(90);
        } else {
            linearLayout.setAlpha(90);
        }
        linearLayout.setVisibility(4);
        linearLayout2 = new ImageView(this.a);
        linearLayout2.setId(3);
        layoutParams6 = new LayoutParams(i3, i);
        layoutParams6.addRule(14);
        layoutParams6.addRule(15);
        linearLayout2.setLayoutParams(layoutParams6);
        linearLayout3 = new TextView(this.a);
        layoutParams7 = new LayoutParams(440, -2);
        layoutParams7.addRule(14);
        layoutParams7.addRule(15);
        linearLayout3.setLayoutParams(layoutParams7);
        linearLayout3.setGravity(17);
        linearLayout3.setText(k.a().a("Hold your card here"));
        linearLayout3.setMaxLines(3);
        linearLayout3.setMinLines(2);
        linearLayout3.setTextColor(-1);
        linearLayout3.setId(12);
        linearLayout4 = new LinearLayout(this.a);
        layoutParams8 = new LayoutParams(i, i4);
        layoutParams8.addRule(14);
        layoutParams8.addRule(6, relativeLayout2.getId());
        linearLayout4.setLayoutParams(layoutParams8);
        linearLayout4.setBackgroundColor(-1);
        linearLayout4.setId(13);
        linearLayout4.setVisibility(4);
        linearLayout5 = new LinearLayout(this.a);
        layoutParams9 = new LayoutParams(i, i4);
        layoutParams9.addRule(14);
        layoutParams9.addRule(8, relativeLayout2.getId());
        linearLayout5.setLayoutParams(layoutParams9);
        linearLayout5.setBackgroundColor(-1);
        linearLayout5.setId(15);
        linearLayout5.setVisibility(4);
        linearLayout6 = new LinearLayout(this.a);
        layoutParams10 = new LayoutParams(i4, i3);
        layoutParams10.addRule(15);
        layoutParams10.addRule(7, relativeLayout2.getId());
        linearLayout6.setLayoutParams(layoutParams10);
        linearLayout6.setBackgroundColor(-1);
        linearLayout6.setId(16);
        linearLayout6.setVisibility(4);
        linearLayout7 = new LinearLayout(this.a);
        layoutParams11 = new LayoutParams(i4, i3);
        layoutParams11.addRule(15);
        layoutParams11.addRule(5, relativeLayout2.getId());
        linearLayout7.setLayoutParams(layoutParams11);
        linearLayout7.setBackgroundColor(-1);
        linearLayout7.setId(14);
        linearLayout7.setVisibility(4);
        linearLayout8 = new LinearLayout(this.a);
        layoutParams12 = new LayoutParams(i4, i);
        layoutParams12.addRule(15);
        layoutParams12.addRule(5, linearLayout2.getId());
        linearLayout8.setLayoutParams(layoutParams12);
        linearLayout8.setBackgroundColor(-1);
        linearLayout8.setId(33);
        linearLayout8.setVisibility(4);
        View linearLayout9 = new LinearLayout(this.a);
        layoutParams12 = new LayoutParams(i4, i);
        layoutParams12.addRule(15);
        layoutParams12.addRule(7, linearLayout2.getId());
        linearLayout9.setLayoutParams(layoutParams12);
        linearLayout9.setBackgroundColor(-1);
        linearLayout9.setId(35);
        linearLayout9.setVisibility(4);
        q = new LinearLayout(this.a);
        layoutParams12 = new LayoutParams(i3, i4);
        layoutParams12.addRule(14);
        layoutParams12.addRule(6, linearLayout2.getId());
        q.setLayoutParams(layoutParams12);
        q.setBackgroundColor(-1);
        q.setId(36);
        q.setVisibility(4);
        View linearLayout10 = new LinearLayout(this.a);
        layoutParams12 = new LayoutParams(i3, i4);
        layoutParams12.addRule(14);
        layoutParams12.addRule(8, linearLayout2.getId());
        linearLayout10.setLayoutParams(layoutParams12);
        linearLayout10.setBackgroundColor(-1);
        linearLayout10.setId(34);
        linearLayout10.setVisibility(4);
        relativeLayout.addView(imageView3);
        relativeLayout.addView(linearLayout);
        relativeLayout.addView(relativeLayout2);
        relativeLayout.addView(linearLayout2);
        relativeLayout.addView(linearLayout3);
        relativeLayout.addView(linearLayout4);
        relativeLayout.addView(linearLayout5);
        relativeLayout.addView(linearLayout6);
        relativeLayout.addView(linearLayout7);
        relativeLayout.addView(linearLayout8);
        relativeLayout.addView(linearLayout9);
        relativeLayout.addView(q);
        relativeLayout.addView(linearLayout10);
        this.b.addView(relativeLayout);
        if (VERSION.SDK_INT >= 13) {
            point2 = new Point();
            this.a.getWindowManager().getDefaultDisplay().getSize(point2);
            i = point2.x;
        } else {
            i = this.a.getWindowManager().getDefaultDisplay().getWidth();
        }
        i = (int) Math.ceil(((double) i) / 6.27d);
        relativeLayout = new RelativeLayout(this.a);
        relativeLayout.setLayoutParams(new LayoutParams(-1, i));
        relativeLayout.setId(11);
        q = new ImageView(this.a);
        ViewGroup.LayoutParams layoutParams13 = new LayoutParams(a(53.0f), a(41.0f));
        layoutParams13.setMargins(0, 18, 15, 0);
        layoutParams13.addRule(11);
        q.setLayoutParams(layoutParams13);
        q.setScaleType(ScaleType.FIT_CENTER);
        q.setImageBitmap(os.a("scanpay_logo"));
        q.setId(7);
        relativeLayout.addView(q);
        this.b.addView(relativeLayout);
        q = new LinearLayout(this.a);
        q.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        q.setGravity(81);
        q.setPadding(10, 0, 10, 0);
        q.setId(37);
        Drawable bitmapDrawable = new BitmapDrawable(Resources.getSystem(), os.a("security_logo"));
        bitmapDrawable.setBounds(0, 0, 40, 40);
        imageView = new TextView(this.a);
        imageView.setCompoundDrawablePadding(10);
        imageView.setCompoundDrawables(bitmapDrawable, null, null, null);
        imageView.setTextColor(-1);
        imageView.setText(k.a().a("Security Message"));
        layoutParams = new LinearLayout.LayoutParams((this.d * 75) / 100, -2);
        layoutParams.setMargins(0, 0, 0, 20);
        imageView.setLayoutParams(layoutParams);
        q.addView(imageView);
        this.b.addView(q);
        q = new RelativeLayout(this.a);
        layoutParams = new LayoutParams(-1, a(50.0f));
        layoutParams.addRule(12, -1);
        q.setLayoutParams(layoutParams);
        q.setGravity(21);
        q.setId(42);
        q.setBackgroundColor(ViewCompat.MEASURED_STATE_MASK);
        float[] fArr = new float[]{6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f};
        float[] fArr2 = new float[]{6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f, 6.0f};
        Drawable shapeDrawable = new ShapeDrawable(new RoundRectShape(fArr, null, fArr2));
        shapeDrawable.getPaint().setColor(Color.parseColor("#777777"));
        shapeDrawable.getPaint().setStrokeWidth(1.0f);
        Drawable shapeDrawable2 = new ShapeDrawable(new RoundRectShape(fArr, null, fArr2));
        shapeDrawable2.getPaint().setColor(Color.parseColor("#555555"));
        shapeDrawable.getPaint().setStrokeWidth(1.0f);
        Drawable stateListDrawable = new StateListDrawable();
        stateListDrawable.addState(new int[]{16842919}, shapeDrawable2);
        stateListDrawable.addState(new int[]{16842910}, shapeDrawable);
        imageView2 = new Button(this.a);
        ViewGroup.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, a(40.0f));
        if (VERSION.SDK_INT >= 16) {
            imageView2.setBackground(stateListDrawable);
        } else {
            imageView2.setBackgroundDrawable(stateListDrawable);
        }
        imageView2.setTextColor(-1);
        imageView2.setLayoutParams(layoutParams14);
        imageView2.setOnClickListener(this.a);
        imageView2.setText(k.a().a("manual entry"));
        q.addView(imageView2, layoutParams14);
        addView(q, layoutParams);
    }

    private int a(float f) {
        return (int) (((double) (this.a.getResources().getDisplayMetrics().density * f)) + 0.5d);
    }
}
