package org.spongycastle.asn1.x9;

import com.thewingitapp.thirdparties.wingitlib.BuildConfig;
import org.spongycastle.asn1.ASN1ObjectIdentifier;

public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier ansi_X9_42;
    public static final ASN1ObjectIdentifier ansi_X9_62;
    public static final ASN1ObjectIdentifier c2onb191v4 = cTwoCurve.branch("8");
    public static final ASN1ObjectIdentifier c2onb191v5 = cTwoCurve.branch("9");
    public static final ASN1ObjectIdentifier c2onb239v4 = cTwoCurve.branch("14");
    public static final ASN1ObjectIdentifier c2onb239v5 = cTwoCurve.branch("15");
    public static final ASN1ObjectIdentifier c2pnb163v1;
    public static final ASN1ObjectIdentifier c2pnb163v2 = cTwoCurve.branch(BuildConfig.VERSION_NAME);
    public static final ASN1ObjectIdentifier c2pnb163v3 = cTwoCurve.branch("3");
    public static final ASN1ObjectIdentifier c2pnb176w1 = cTwoCurve.branch("4");
    public static final ASN1ObjectIdentifier c2pnb208w1 = cTwoCurve.branch("10");
    public static final ASN1ObjectIdentifier c2pnb272w1 = cTwoCurve.branch("16");
    public static final ASN1ObjectIdentifier c2pnb304w1 = cTwoCurve.branch("17");
    public static final ASN1ObjectIdentifier c2pnb368w1 = cTwoCurve.branch("19");
    public static final ASN1ObjectIdentifier c2tnb191v1 = cTwoCurve.branch("5");
    public static final ASN1ObjectIdentifier c2tnb191v2 = cTwoCurve.branch("6");
    public static final ASN1ObjectIdentifier c2tnb191v3 = cTwoCurve.branch("7");
    public static final ASN1ObjectIdentifier c2tnb239v1 = cTwoCurve.branch("11");
    public static final ASN1ObjectIdentifier c2tnb239v2 = cTwoCurve.branch("12");
    public static final ASN1ObjectIdentifier c2tnb239v3 = cTwoCurve.branch("13");
    public static final ASN1ObjectIdentifier c2tnb359v1 = cTwoCurve.branch("18");
    public static final ASN1ObjectIdentifier c2tnb431r1 = cTwoCurve.branch("20");
    public static final ASN1ObjectIdentifier cTwoCurve;
    public static final ASN1ObjectIdentifier characteristic_two_field = id_fieldType.branch(BuildConfig.VERSION_NAME);
    public static final ASN1ObjectIdentifier dhEphem = x9_42_schemes.branch(BuildConfig.VERSION_NAME);
    public static final ASN1ObjectIdentifier dhHybrid1 = x9_42_schemes.branch("4");
    public static final ASN1ObjectIdentifier dhHybrid2 = x9_42_schemes.branch("5");
    public static final ASN1ObjectIdentifier dhHybridOneFlow = x9_42_schemes.branch("6");
    public static final ASN1ObjectIdentifier dhOneFlow = x9_42_schemes.branch("3");
    public static final ASN1ObjectIdentifier dhSinglePass_cofactorDH_sha1kdf_scheme = x9_63_scheme.branch("3");
    public static final ASN1ObjectIdentifier dhSinglePass_stdDH_sha1kdf_scheme;
    public static final ASN1ObjectIdentifier dhStatic;
    public static final ASN1ObjectIdentifier dhpublicnumber;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA1 = new ASN1ObjectIdentifier(id_ecSigType + ".1");
    public static final ASN1ObjectIdentifier ecdsa_with_SHA2;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA224;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA256 = ecdsa_with_SHA2.branch(BuildConfig.VERSION_NAME);
    public static final ASN1ObjectIdentifier ecdsa_with_SHA384 = ecdsa_with_SHA2.branch("3");
    public static final ASN1ObjectIdentifier ecdsa_with_SHA512 = ecdsa_with_SHA2.branch("4");
    public static final ASN1ObjectIdentifier ellipticCurve;
    public static final ASN1ObjectIdentifier gnBasis = id_fieldType.branch("2.3.1");
    public static final ASN1ObjectIdentifier id_dsa = new ASN1ObjectIdentifier("1.2.840.10040.4.1");
    public static final ASN1ObjectIdentifier id_dsa_with_sha1 = new ASN1ObjectIdentifier("1.2.840.10040.4.3");
    public static final ASN1ObjectIdentifier id_ecPublicKey;
    public static final ASN1ObjectIdentifier id_ecSigType = ansi_X9_62.branch("4");
    public static final ASN1ObjectIdentifier id_fieldType;
    public static final ASN1ObjectIdentifier id_publicKeyType;
    public static final ASN1ObjectIdentifier mqv1 = x9_42_schemes.branch("8");
    public static final ASN1ObjectIdentifier mqv2 = x9_42_schemes.branch("7");
    public static final ASN1ObjectIdentifier mqvSinglePass_sha1kdf_scheme = x9_63_scheme.branch("16");
    public static final ASN1ObjectIdentifier ppBasis = id_fieldType.branch("2.3.3");
    public static final ASN1ObjectIdentifier prime192v1;
    public static final ASN1ObjectIdentifier prime192v2 = primeCurve.branch(BuildConfig.VERSION_NAME);
    public static final ASN1ObjectIdentifier prime192v3 = primeCurve.branch("3");
    public static final ASN1ObjectIdentifier prime239v1 = primeCurve.branch("4");
    public static final ASN1ObjectIdentifier prime239v2 = primeCurve.branch("5");
    public static final ASN1ObjectIdentifier prime239v3 = primeCurve.branch("6");
    public static final ASN1ObjectIdentifier prime256v1 = primeCurve.branch("7");
    public static final ASN1ObjectIdentifier primeCurve;
    public static final ASN1ObjectIdentifier prime_field;
    public static final ASN1ObjectIdentifier tpBasis = id_fieldType.branch("2.3.2");
    public static final ASN1ObjectIdentifier x9_42_schemes;
    public static final ASN1ObjectIdentifier x9_63_scheme;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10045");
        ansi_X9_62 = aSN1ObjectIdentifier;
        aSN1ObjectIdentifier = aSN1ObjectIdentifier.branch("1");
        id_fieldType = aSN1ObjectIdentifier;
        prime_field = aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier = ansi_X9_62.branch(BuildConfig.VERSION_NAME);
        id_publicKeyType = aSN1ObjectIdentifier;
        id_ecPublicKey = aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier = id_ecSigType.branch("3");
        ecdsa_with_SHA2 = aSN1ObjectIdentifier;
        ecdsa_with_SHA224 = aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier = ansi_X9_62.branch("3");
        ellipticCurve = aSN1ObjectIdentifier;
        aSN1ObjectIdentifier = aSN1ObjectIdentifier.branch("0");
        cTwoCurve = aSN1ObjectIdentifier;
        c2pnb163v1 = aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier = ellipticCurve.branch("1");
        primeCurve = aSN1ObjectIdentifier;
        prime192v1 = aSN1ObjectIdentifier.branch("1");
        aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        x9_63_scheme = aSN1ObjectIdentifier;
        dhSinglePass_stdDH_sha1kdf_scheme = aSN1ObjectIdentifier.branch(BuildConfig.VERSION_NAME);
        aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.840.10046");
        ansi_X9_42 = aSN1ObjectIdentifier;
        dhpublicnumber = aSN1ObjectIdentifier.branch("2.1");
        aSN1ObjectIdentifier = ansi_X9_42.branch("3");
        x9_42_schemes = aSN1ObjectIdentifier;
        dhStatic = aSN1ObjectIdentifier.branch("1");
    }
}
